### ISSUE TITLE
pip install . is not installting tomo_processing module

### ISSUE THREAD

**Issue by truatpasteurdotfr** [teamtomo/membrain-seg#18]
Hi

I have installed membrain-seg to a shared space for our group member and I had to use `pip install .` instead of `pip install -e .` to copy the python modules to the `miniconda3/envs/membrain-seg/lib/python3.9/site-packages` folder.
The `membrain_seg` is copied but not `tomo_preprocessing`.

Cheers

Tru

**Comment by LorenzLamm** [comment]
Hi Tru,
Thanks a lot for raising this issue! 

Apparently installing via `pip install .` using the `pyproject.toml` file only supports to install a single package -- in this case membrain_seg, but neither the `tomo_preprocessing` nor the `annotations` package.

We will probably restructure the package to have one main package (`membrain_seg`) with multiple sub-packages.

Will try to implement this as soon as possible and get back to you.

Best,
Lorenz

**Comment by alisterburt** [comment]
closed by #19 - `pip install .` should now work 🙂
