### ISSUE TITLE
Feature Suggestion: Add CLI flag to turn off test_time_augmentation

### ISSUE THREAD

**Issue by MSiggel** [teamtomo/membrain-seg#30]
Currently, there is no command line flag to turn off the 8-fold augmentation (test_time_augmentation)
It would be helpful to access this parameter from the CLI for rapid testing.

**Comment by LorenzLamm** [comment]
Thanks for bringing this up!

From my experience, the test time augmentation is squeezing out a tiny bit of segmentation improvement, but does not change the output drastically.
I still recommend using it for a segmentation to work with, but I agree that it would be beneficial to deactivate this option for having a quick look at the performance.

I'll implement this option within the next days :)

**Comment by LorenzLamm** [comment]
Took longer than expected to implement this, but now the `--test-time-augmentation` (default) and `--no-test-time-augmentation` flags control whether test time augmentation is performed:
https://github.com/teamtomo/membrain-seg/blob/main/docs/Usage/Segmentation.md#more-membrain-segment-arguments
