### ISSUE TITLE
documentation typos

### ISSUE THREAD

**Issue by 3P1L** [teamtomo/membrain-seg#35]
Hey Lorenz!

great work! Right out of the box, beautiful segmentation of mouse liver membranes! ;-) 

I just found that in the documentation there are some typos:

--some_command_input

should be

--some-command-input

e.g.

No such option: --input_tomogram Did you mean --input-tomogram?

Best,

Philipp.

**Comment by LorenzLamm** [comment]
Thanks for your feedback Philipp! :)
And thanks for pointing out the typos. Tried to fix all of them in the new PR we just merged: https://github.com/teamtomo/membrain-seg/pull/36
