### ISSUE TITLE
Help display shows unavailable "predict" command

### ISSUE THREAD

**Issue by m-albert** [teamtomo/membrain-seg#38]
Hey, thanks for working on this and sharing it :)

Just wanted to quickly report here that the cli usage instructions show a command "predict", which is not available. Probably it'd be less confusing if it said e.g. "segment".

<img width="422" alt="image" src="https://github.com/teamtomo/membrain-seg/assets/12528388/0beefbe0-e9cb-413f-8ea1-6263badd0a86">

**Comment by alisterburt** [comment]
Respectfully disagree, predict is much more common for CNNs - the model 'predicts' the segmentation based on the tomogram

**Comment by m-albert** [comment]
Oh yes totally agree, it's just that I tried out the command and it wasn't available, while segment was :)

**Comment by alisterburt** [comment]
Gotcha!Sent from mobile - apologies for brevityOn 5 Oct 2023, at 21:43, Marvin Albert ***@***.***> wrote:﻿
Oh yes totally agree, it's just that I tried out the command and it wasn't available, while segment was :)
