### ISSUE TITLE
docs setup with mkdocs-material

### ISSUE THREAD

**Issue by alisterburt** [teamtomo/membrain-seg#57]
The current documentation is really nice but is only accessible via the readme through github and not the easiest to browse

There is some nice infrastructure in teamtomo which can make a site available at `teamtomo.org/package-name` 

We would need to 
1. adopt the teamtomo docs config https://github.com/teamtomo/starfile/blob/main/mkdocs.yml
2. add a github actions workflow for building and deploying the docs https://github.com/teamtomo/starfile/blob/main/.github/workflows/build-and-deploy-docs.yml

Thoughts @LorenzLamm ? Maybe this should wait until the package is more independent of membrain

**Comment by LorenzLamm** [comment]
I think it would at any point be cool to have good documentation that is easy to use (independent of how much we want to move away from membrain).

mkdocs & github actions workflow are already in the repository:
https://github.com/teamtomo/membrain-seg/blob/main/.github/workflows/build-and-deploy-docs.yml
https://github.com/teamtomo/membrain-seg/blob/main/mkdocs.yml

I'm not familiar enough to see what's missing to get it automatically deployed, but maybe you can spot the issue?

**Comment by alisterburt** [comment]
I'll have a play with this now

**Comment by alisterburt** [comment]
looks like the documentation itself was fine but the package wasn't being installed in the workflow - must have been commented out before package was pip installable locally... I also updated the config to remove a few warnings

**Comment by alisterburt** [comment]
also had to update the repo settings to deploy from the `gh-pages` branch
![image](https://github.com/teamtomo/membrain-seg/assets/7307488/5eafab06-3fbb-44fd-a79b-00b4e4732e3d)

**Comment by alisterburt** [comment]
docs are available at https://teamtomo.org/membrain-seg/

can you hold off on publicising this until we've finished discussing the package independence thing? The installation instructions are also a little outdated :-)

**Comment by LorenzLamm** [comment]
Amazing! Thanks a lot for taking care of this!
And yes, let's hold this for a while :)
