### ISSUE TITLE
MemBrain-seg installation documentation problem

### ISSUE THREAD

**Issue by TomCrey** [teamtomo/membrain-seg#78]
Hi TeamTomo, 

I think there's a problem with the membrain-seg installation documentation (https://teamtomo.org/membrain-seg/installation/) because the page is in error 404, which wasn't the case last week...
If you could fix this so that the installation instructions are available again, that would be great! 

Thanks,
Tom

**Comment by LorenzLamm** [comment]
Thanks a lot for pointing this out @TomCrey! 
It looks like the domain of the generated docs moved from https://teamtomo.org/membrain-seg/installation/ 
to 
https://teamtomo.github.io/membrain-seg/installation/

I just changed the links to the new domain (PR https://github.com/teamtomo/membrain-seg/pull/79), so everything should work again :)

**Comment by TomCrey** [comment]
Yes, everything works perfectly, thank you very much @LorenzLamm !
