### ISSUE TITLE
Thresholds input file specification needs fix

### ISSUE THREAD

**Issue by kimdn** [teamtomo/membrain-seg#80]
* membrain-seg version:
commit 0a87963b798ee2652bdbe07f467e04e87d951a54
Author: LorenzLamm <34575029+LorenzLamm@users.noreply.github.com>
Date:   Tue Jul 16 15:36:42 2024 +0200

* Python version:
Python 3.9.5

* Operating System:
linux

### Description

According to
```
membrain thresholds --scoremap-path <path-to-scoremap>
        --thresholds -1.5
```
I did 

`membrain thresholds --scoremap-path outputs/2024_06_06-MED4_10p4_Apix_MED4_TS_11_SIRT_CTF_no_Au_rec/2024_06_06-MED4_10p4_Apix_MED4_TS_11_SIRT_CTF_no_Au_rec_scores.mrc --thresholds -1.5`

but MemBrain-seg seeks
/predictions (hardcoded?)

![Screenshot 2024-09-05 at 7 37 02 PM](https://github.com/user-attachments/assets/b05ea990-9898-4b7b-b767-95b0f392092c)

**Comment by LorenzLamm** [comment]
Hey @kimdn,
Thanks a lot for raising this.

You can control the output folder in the command line via the flag `--out-folder /path/to/your/output`
If no argument is provided here, it will default to `./predictions`, i.e. also the default output folder for segmentations.

E.g. for your case, you could do
`membrain thresholds --scoremap-path outputs/2024_06_06-MED4_10p4_Apix_MED4_TS_11_SIRT_CTF_no_Au_rec/2024_06_06-MED4_10p4_Apix_MED4_TS_11_SIRT_CTF_no_Au_rec_scores.mrc --thresholds -1.5 --out-folder outputs/2024_06_06-MED4_10p4_Apix_MED4_TS_11_SIRT_CTF_no_Au_rec/` 
and it should work just fine.

To avoid the error, maybe we should automatically create the output folder?
I should definitely add the out_folder argument to the documentation.

Let me know if this helps. :)

**Comment by kimdn** [comment]
> --out-folder outputs/2024_06_06-MED4_10p4_Apix_MED4_TS_11_SIRT_CTF_no_Au_rec/

Thank you @LorenzLamm 

Adding
`--out-folder outputs/2024_06_06-MED4_10p4_Apix_MED4_TS_11_SIRT_CTF_no_Au_rec/`
works.

Yes, either adding document or adding exception handling like 'MemBrain-seg' can't find score file in default "predictions" folder. Consider to specify --out-folder as you did for "membrain segment" might be nice.

Thank you for making MemBrain-seg. Just using your latest pre-trained model segmented our target membrane well.
